version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_service
    restart: always
    env_file:
      - ${ENV_FILE:-.env.dev}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: redis_service
    restart: always
    env_file:
      - ${ENV_FILE:-.env.dev}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

volumes:
  postgres_data:
  redis_data:

networks:
  app_network:
    driver: bridge
