spring:
    application:
        name: AuthenticationService

    security:
        user:
            name: admin
            password: admin123

server:
  port: 8081

logging:
  level:
    '[org.springframework.security]': trace
