spring:
    application:
        name: AuthenticationService

    security:
        user:
            name: admin
            password: admin123

    kafka:
      producer:
        bootstrap-servers:
        - localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer

    data:
      redis:
        host: localhost
        port: 6379
        timeout: 60000

server:
  port: 8081

logging:
  level:
    '[org.springframework.security]': info
